settings:
  title: 'Web Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: favicon.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: lewlab-wustl-edu # unique identifier
    name: Lew Lab main
    description: '' # default=empty
    url: 'https://lewlab.wustl.edu/favicon.svg' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: github-com-Lew-Lab
    name: Lew Lab GitHub
    url: 'https://github.com/Lew-Lab'
    method: GET
    expectStatus: 200

  - id: osf-io-utjmr
    name: Lew Lab OSF
    url: 'https://osf.io/utjmr/'
    method: GET
    expectStatus: 200

  - id: osf-io-download-3t7xj
    name: Lew Lab OSF-Box download
    url: 'https://osf.io/download/3t7xj/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: lewlab-com
    name: Lew Lab mirror
    url: 'https://lewlab.com'
    method: GET
    expectStatus: 200

  - id: ip-lewlab-com-favicon-ico
    name: This status page
    url: 'https://ip.lewlab.com/favicon.ico'
    method: GET
    expectStatus: 200
    linkable: false
